version: "3.6"

services:
  db:
    container_name: ${PROJECT_NAME}-db
    image: mariadb:10.8.2
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - main

  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    environment:
      SERVICE_NAME: app
      PHP_IDE_CONFIG: "serverName=app"
    restart: always
    volumes:
      - ./src/:/var/www
      - ./docker/app/ini/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - "db"
    networks:
      - main

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:1.21
    restart: always
    environment:
      BACKEND: "app"
    depends_on:
      - "app"
    ports:
      - "127.0.0.1:${NGINX_PORT}:80"
    volumes:
      - ./src/:/var/www:ro
      - ./docker/nginx/templates/:/etc/nginx/templates:ro
    networks:
      - main

networks:
  main:
    name: "${PROJECT_NAME}-network"

volumes:
  db_data:
